apiVersion: template.openshift.io/v1
kind: Template
labels:
  template: nfs-pv-pvc
message: Your PersistentVolume & PersistentVolumeClaim has been created in your project.  # 应用发布完成后的提示信息，可以用来写应用访问地址，数据库的访问信息之类，建议完善。
metadata:
  annotations: # annotations 里面的都是非必备项
    description: An example template. For more information about
      using this template, see https://github.com/cai11745/k8s-ocp-yaml/blob/master/openshift-docs/2019-08-08--how-to-write-openshift-template.md. # template 被选中时候的初始描述
    iconClass: icon-rh-tomcat  # 模板的图标，库在这 https://rawgit.com/openshift/openshift-logos-icon/master/demo.html
    openshift.io/display-name: Create nfs persistent volume # 如果设置了这项，这个template在web上显示的名称是这个，不再是metadata.name内容
  name: nfs-pv-pvc
objects:  # 以下为资源集合，可以添加各种支持的资源类型，每-apiVersion 就是一个，可以是dc，configmap，imagestream等
- apiVersion: v1
  kind: PersistentVolume
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      name: ${APPLICATION_NAME}
  spec:
    accessModes:
    - ReadWriteMany
    capacity:
      storage: ${VOLUME_CAPACITY}
    nfs:
      path: ${NFS_SERVER_PATH}
      server: ${NFS_SERVER_ADDR}
    persistentVolumeReclaimPolicy: Retain
- apiVersion: v1
  kind: PersistentVolumeClaim
  metadata:
    name: ${APPLICATION_NAME}
    labels:
      name: ${APPLICATION_NAME}
  spec:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: ${VOLUME_CAPACITY}
    selector:
      matchLabels:
        name: ${APPLICATION_NAME}
parameters:  #以下信息将显示在web页面，通过页面把参数传递到上面的object中。
- description: The name for the application.
  displayName: Application Name
  name: APPLICATION_NAME   #对应上面object里调用的变量，把值传递上去。
  required: true   #表示必填项
  value: nfs-share   #默认值
- description: Volume space available for data, e.g. 512Mi, 2Gi.
  displayName: Volume Capacity
  name: VOLUME_CAPACITY
  required: true
  value: 1Gi
- description: Nfs server hostname or ip addr. e.g. 192.168.1.101
  displayName: Nfs server address.
  name: NFS_SERVER_ADDR
  required: true
- description: Nfs server share path. e.g. /nfs-share1
  displayName: Nfs server share path.
  name: NFS_SERVER_PATH
  required: true
