apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
  labels:
    name: demo-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: 1Gi
  nfs:
    path: /opt/add-dev/nfs/
    server: 192.168.4.133
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-demo-volume 
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      name: demo-pv

