apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: demo-resources-limit
  name: demo-resources-limit
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-resources-limit
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo-resources-limit
    spec:
      containers:
      - image: tomcat
        name: demo-resources-limit
        ports:
        - containerPort: 8080
        resources:     #限制container的资源
          requests:   #请求的资源
            cpu: 10     #请求节点最低cpu可用10核，故意设置大点让他调度失败
            memory: 30Gi
          limits:     #pod最大可以使用的资源
            cpu: 16
            memory: 40Gi

