apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: demo-configmap
  name: demo-configmap
spec:
  replicas: 1
  selector:
    matchLabels:
      run: demo-configmap
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: demo-configmap
    spec:
      containers:
      - image: tomcat
        name: demo-configmap
        ports:
        - containerPort: 8080
        env:
          - name: SPECIAL_LEVEL_KEY
            valueFrom:
              configMapKeyRef:
                name: special-config
                key: special.how

